name: {{projectName}}
description: >
  A library useful for applications or for sharing on pub.dartlang.org.
version: 0.0.1
#author: {{author}} <email@example.com>
#homepage: https://www.example.com
#dependencies:
#  lib_name: any
dev_dependencies:
  unittest: '>=0.11.0 <0.12.0'
