# Copyright (c) 2014, Google Inc. Please see the AUTHORS file for details.
# All rights reserved. Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

name: stagehand
# When changing this version, change the lib/src/cli_app.dart version as well.
version: 0.2.5+2
description: >
  A scaffolding generator for your Dart projects. Stagehand helps you get set
  up!
homepage: http://stagehand.pub
authors:
- Seth Ladd <sethladd@google.com>
- Devon Carew <devoncarew@google.com>

environment:
  sdk: '>=1.9.0 <2.0.0'

# Add the bin/stagehand.dart script to the scripts pub installs.
executables:
  stagehand:

dependencies:
  args: '>=0.12.0+1 <0.14.0'
  crypto: ^0.9.0
  http: ^0.11.0
  path: ^1.3.0
  usage: ^1.0.0

dev_dependencies:
  browser: ^0.10.0
  ghpages_generator: ^0.2.4
  grinder: ^0.8.0
  test: ^0.12.0
  yaml: ^2.1.2
