# Copyright (c) 2014, Google Inc. Please see the AUTHORS file for details.
# All rights reserved. Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

name: stagehand
description: >
  A scaffolding generator for your Dart projects. Stagehand helps you get set
  up!
# After changing the version, run `pub run build_runner build`.
version: 3.3.11
homepage: https://github.com/dart-lang/stagehand

environment:
  # Make sure this Dart SDK version is no higher than the stable Flutter Dart
  # SDK version to prevent errors when using Stagehand from inside VSCode's
  # Dart and Flutter plugins. For more detail, please see:
  # https://github.com/dart-lang/stagehand/issues/617
  #
  # Also make sure this minimum sdk version is reflected in `.travis.yml`.
  sdk: '>=2.10.0 <3.0.0'

# Add the bin/stagehand.dart script to the scripts pub installs.
executables:
  stagehand:

dependencies:
  args: ^1.5.0
  http: ^0.12.0
  path: ^1.7.0
  pedantic: ^1.9.0
  usage: ^3.4.0

dev_dependencies:
  build: ^1.1.0
  build_config: ^0.4.0
  build_runner: ^1.6.0
  build_version: ^2.0.0
  glob: ^1.1.5
  grinder: ^0.8.0
  source_gen: ^0.9.0
  test: ^1.6.0
  yaml: ^2.1.2
