name: '{{projectName}}'
version: 0.0.1
description: >
  An absolute bare-bones web app.
#author: {{author}} <email@example.com>
#homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: '>=0.10.0+2 <0.11.0'
