name: __projectName__
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: __author__ <__email__>

environment:
  sdk: '>=2.6.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0
  pedantic: ^1.8.0
