name: {{projectName}}
version: 0.0.1
description: A simple hello world command-line application.
#author: First Last <email@example.com>
#homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
#dependencies:
#  foo_bar: any
