name: __projectName__
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com
# author: __author__ <__email__>

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  args: ^1.5.0
  shelf: ^0.7.2

dev_dependencies:
  pedantic: ^1.7.0
