name: __projectName__
description: A web server built using the shelf package.
version: 0.0.1
#homepage: https://www.example.com
#author: __author__ <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  args: ^0.13.7
  shelf: ^0.6.0

#dev_dependencies:
#  test: ^0.12.0
