name: __projectName__
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  args: ^1.6.0
  shelf: ^0.7.5

dev_dependencies:
  pedantic: ^1.9.0
