name: __projectName__
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  angular: ^6.0.0
  angular_components: ^1.0.2

dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.9.0
  build_test: ^1.0.0
  build_web_compilers: ^2.10.0
  pedantic: ^1.9.0
  test: ^1.6.3
