name: __projectName__
description: A web app that uses AngularDart Components
version: 0.0.1
#homepage: https://www.example.com
#author: __author__ <email@example.com>

environment:
  sdk: '>=2.0.0-dev.3.0 <2.0.0'

dependencies:
  angular: ^5.0.0-alpha
  angular_components: ^0.9.0-alpha

dev_dependencies:
  angular_test: ^2.0.0-alpha
  build_runner: ^0.7.8
  build_test: ^0.10.0
  build_web_compilers: ^0.2.1
  test: ^0.12.30

dependency_overrides:
  analyzer: ^0.31.0-alpha.1
