name: 'angular2 gnome template'
version: 0.0.1
description: Gnome template
author: Sanford Redlich <siredlich@gmail.com>
environment:
  sdk: '^1.9.3'
dependencies:
  angular2: "2.0.0-alpha.25"
  browser: "^0.10.0"
dev_dependencies:
  test: any