name: '{{projectName}}'
version: 0.0.1
description: >
  A minimal web app for the developer that doesnâ€™t want to be confused by too
  much going on.
#author: {{author}} <email@example.com>
#homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  sass: '>=0.4.0 <0.5.0'
  script_inliner: '>=0.0.3 <0.1.0'
  route_hierarchical: '>=0.5.0 <0.6.0'
transformers:
  - sass:
      style: compressed
  - script_inliner
