name: '{{projectName}}'
version: 0.0.1
description: >
  A minimal web app for the developer that doesnâ€™t want to be confused by too
  much going on.
#author: {{author}} <email@example.com>
#homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: '>=0.10.0 <0.11.0'
  sass: '>=0.4.0 <0.5.0'
  script_inliner: '>=1.0.0 <2.0.0'
  route_hierarchical: '>=0.5.0 <0.7.0'
transformers:
- script_inliner
#- sass:
#    style: compressed
